[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.64.1"
  HUGO_ENABLEGITINFO = "true"
  ODE_VERSION = "18"

[context.production.environment]
  HUGO_ENV = "production"
  HUGO_VERSION = "0.64.1"
